title: AI Data Production Landscape
description: A comprehensive analysis of artificial intelligence data production systems and methodologies

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# SEO settings
url: "https://username.github.io"
baseurl: "/ai-data-production-landscape"

# Jekyll settings
permalink: pretty
timezone: UTC

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Collections
collections:
  docs:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"

# Custom variables
show_excerpts: false
minima:
  social_links:
    github: username/ai-data-production-landscape